### ISSUE TITLE
why not just use the SPORE spec ? 

### ISSUE THREAD

**Issue by eiro** [tokuhirom/ph#2]
hello,

do you know spore? is there something wrong with the github spec ?

https://metacpan.org/release/Net-HTTP-Spore
https://github.com/SPORE/api-description/blob/master/services/github.json

regards
marc

**Comment by tokuhirom** [comment]
spore is too heavy library for me. i seem, any command line utilities SHOULD NOT use Moose and MooseX::\* libraries for fast operation.

**Comment by eiro** [comment]
right ... maybe what if a Package::Stash version exists ?
